[package]
name = "boolean"
version = "0.1.0"
authors = ["Eric Douglass <dougli1sqrd+git@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
